CREATE TABLE
	IF NOT EXISTS "restaurant_table" (id SERIAL PRIMARY KEY, number INT UNIQUE NOT NULL);

ALTER TABLE "order"
ADD COLUMN IF NOT EXISTS id_table INT REFERENCES restaurant_table (id),
ADD COLUMN IF NOT EXISTS installation_date TIMESTAMP WITHOUT TIME ZONE,
ADD COLUMN IF NOT EXISTS departure_date TIMESTAMP WITHOUT TIME ZONE;
